apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: services.127.0.0.1.nip.io
      http:
        paths:
          - path: /notification/?(.*)
            pathType: Prefix
            backend:
              service:
                name: notification
                port:
                  number: 80
          - path: /order/?(.*)
            pathType: Prefix
            backend:
              service:
                name: order
                port:
                  number: 80
          - path: /lager/?(.*)
            pathType: Prefix
            backend:
              service:
                name: lager
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: app-db
type: Opaque
stringData:
  url: jdbc:postgresql://postgres-postgresql.data.svc.cluster.local:5432/appdb
  username: app
  password: app123
