apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lager
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: lager
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
