spring:
  application:
    name: ${APP_NAME:notification}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DATABASE_USERNAME:app}
    password: ${DATABASE_PASSWORD:app123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: notification
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://tempo.monitoring.svc.cluster.local:4318/v1/traces
  observations:
    enable:
      rabbitmq: true
      http: true
      jdbc: true

server:
  port: ${PORT:3000}
