kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lagerr
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
