apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:cemildo/lagerr.git
    targetRevision: main
    path: services/notification/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
