apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-and-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: git@github.com:cemildo/lagerr.git
    targetRevision: main
    path: infra/ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
