apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: default
type: Opaque
stringData:
  RABBITMQ_HOST: rabbitmq.messaging.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: app
  RABBITMQ_PASSWORD: app123


---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-amqp
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30672   # choose an open port

