apiVersion: monitoring.coreos.com/v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: notification
